config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # This is our landing page
  root to: 'pages#home'
  # We're using all our routes for courts

  resources :users, only: [:show]

  resources :courts do
    resources :reservations, only: [:create]
  end
  resources :reservations, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/court.rb
class Court < ApplicationRecord
  has_one_attached :photo
  has_many :reservations
  belongs_to :user
  validates :name, :location, :pricing, :capacity, :photo, presence: true
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :court
  validates :start_date, :end_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reservations, dependent: :destroy
  has_many :courts, through: :reservations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # [...]
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name])
  end

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/courts_controller.rb
class CourtsController < ApplicationController
  before_action :set_court, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: :index

  def index
    # @courts = Court.all
    # nós iremos chamar em nosso court_policy.rb o metodo resolve, que retorna scope.all ( o mesmo que Court.all)
    @courts = policy_scope(Court)
  end

  def show
    @user = current_user
    @reservation = Reservation.new
    @reservation.court = @court
    @reservations = Reservation.where(court_id: @court.id)
    @users = User.all

    @courts = Court.all
    @markers = @court.geocode.map do |court|
      {
        lat: @court.latitude,
        lng: @court.longitude
      }
    end
  end

  def new
    @court = Court.new
    authorize @court
  end

  def create
    @court = Court.new(court_params)
    @court.availability = ActiveModel::Type::Boolean.new.cast(params[:court][:availability])
    @court.user = current_user
    authorize @court

    if @court.save!
      redirect_to courts_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @court.availability = ActiveModel::Type::Boolean.new.cast(params[:court][:availability])
    @court.update(court_params)
    if @court.save!
      redirect_to court_path(@court)
    else
      render :edit
    end
  end

  def destroy
    @court.destroy
    redirect_to courts_path
  end

  private

  def set_court
    @court = Court.find(params[:id])
    authorize @court
  end

  def court_params
    params.require(:court).permit(:name, :location, :availabity, :pricing, :capacity, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def create
    @court = Court.find(params[:court_id])
    @reservation = Reservation.new(reservation_params)
    @reservation.user = current_user
    @reservation.court = @court
    authorize @reservation
    if @reservation.save!
      redirect_to court_path(@court)
    else
      redirect_to courts_path
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    authorize @reservation
    @reservation.destroy
    redirect_to court_path(@reservation.court)
  end

  private

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @users = User.all
    @reservations = Reservation.all
    @courts = Court.all
    @user = User.find(params[:id])
    authorize @user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courts/_form.html.erb
<%= simple_form_for(court) do |f| %>
  <%= f.input :name %>
  <%= f.input :location %>
  <%= f.input :pricing %>
  <%= f.input :capacity %>
  <%= f.input :photo, as: :file %>
  <%= f.submit class: "btn-success text-light p-2 shadow-none" %>
<% end %>

app/views/courts/edit.html.erb
<%= render 'shared/navbar' %>
<%= render 'form', court: @court %>

app/views/courts/index.html.erb
<%= render 'shared/navbar' %>

<main class="d-flex justify-content-center align-items-center pb-3">
  <section>
    <ul class="p-0 my-5 d-flex w-80 flex-wrap justify-content-center">
    <% @courts.each do |court| %>
      <li>
      <div class='p-3 m-4 border rounded'>
        <div class="upper">
         <%= link_to court_path(court) do %>
          <%= cl_image_tag court.photo.key, height: 300, width: 400 %>
         <% end %>
        </div>
        <div class="lower text-left my-3">
          <h4> <%= link_to court.name, court_path(court), class: "text-dark"  %> </h3>
          <p class="text-dark"> R$<%= court.pricing %>0 </p>
        </div>
      </div>
      </li>
    <% end %>
    </ul>

    <% if policy(Court).new? %>
    <%= link_to "Add a court!", new_court_path, class: "btn-primary p-3" %>
    <% end %>
  </section>
</main>

app/views/courts/new.html.erb
<%= render 'shared/navbar' %>
<%= render 'form', court: @court %>

app/views/courts/show.html.erb
<%= render 'shared/navbar' %>

<main class="mb-4">
<h1> <%= @court.name %> </h1>
<h2> by  <%= link_to @court.user.first_name, user_path(@court.user) %> </h2>

<% if policy(@court).edit? %>
  <%= link_to "Edit", edit_court_path(@court) %>
<% end %>

<% if policy(@court).destroy? %>
<%= link_to "Delete",
            court_path(@court),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
<% end %>

<ul>
  <li> <%= cl_image_tag @court.photo.key, height: 300, width: 400 %> </li>
  <li> <strong> Location: </strong> <%= @court.location %>
  <div class="d-flex justify-content-center align-items-center">
  <div  id="map"
     style="width: 600px; height: 300px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </li>
  </div>
  <li> <strong>Capacity:</strong> <%= @court.capacity %> </li>
  <li> <strong>Price: </strong> R$ <%= @court.pricing %> </li>
</ul>

<ul>
<% @reservations.each do |reservation| %>
  <% @users.each do |user| %>
  <% if reservation.user_id == user.id %>
  <li><%= user.first_name %> booked <%= @court.name %> from <%= reservation.start_date %> to <%= reservation.end_date %>
        <% if policy(reservation).destroy? %>
        <%= link_to "Delete",
            reservation_path(reservation),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
        <% end %>
  </li>
  <% end %>
  <% end %>
<% end %>
</ul>

<%= simple_form_for([@court, @reservation]) do |f| %>
  <%= f.input :start_date, as: :datetime, html5: true %>
  <%= f.input :end_date, as: :datetime, html5: true %>
  <%= f.submit class: "btn-success text-light p-2 shadow-none" %>
<% end %>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SPORTCourtFinder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'shared/flashes' %>
    <%= yield %>

  </body>
</html>

app/views/pages/home.html.erb
<main class="container d-flex justify-content-center align-items-center vh-100">
  <section>
    <div>
     <%= image_tag "https://res.cloudinary.com/db7q8jblt/image/upload/v1637937288/development/logo_SCF_vefgpc.jpg", id: "logo" %>
    </div>

    <div class="btn btn-success my-5">
      <% if user_signed_in? %>
      <%= link_to "Enter!", user_path(current_user), class: "text-light" %>
      <% else %>
      <%= link_to "Login!", new_user_session_path, class: "text-light" %>
      <% end %>
    </div>
  </section>
</main>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <%= link_to "/", class: "navbar-brand" do %>
     <%= image_tag "https://res.cloudinary.com/db7q8jblt/image/upload/v1637864527/development/logo_vsn5eu.jpg", id: "logo" %>
  <% end %>

  <div class="nav-item active">
    <%= link_to "Browse Courts", courts_path, class:  "btn-primary p-3" %>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto flex align-items-center">
      <% if user_signed_in? %>
        <li class="nav-item active mr-2">
          Hi, <%= current_user.first_name %>!
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Mr._Smiley_Face.svg/480px-Mr._Smiley_Face.svg.png", class: "avatar dropdown-toggle opacity-0", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Your reservations", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Add a court", new_court_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'shared/navbar' %>

<h2> <%= @user.first_name %></h2>

<h3> Reservations: </h3>
<ul>
<% @reservations.each do |reservation|%>
  <% if @user.id == reservation.user_id %>
  <li> <strong> <%= @user.first_name %> </strong> booked <%= reservation.court.name %> from <%= reservation.start_date %> to <%= reservation.end_date %>  </strong> </li>
  <% end %>
<% end %>
</ul>